### ISSUE TITLE
之前在论坛说过 就是Number类型的实体无法设置值

### ISSUE THREAD

**Issue by xxlxmd** [knoop7/zhipuai#1]
此错误来自自定义集成。

日志记录器: custom_components.zhipuai.const
来源: custom_components/zhipuai/conversation.py:248
集成: 智谱清言 (文档, 问题)
首次出现: 22:00:50 (3 次总计出现)
上次记录: 22:30:29

工具调用失败: Domain not supported: number
工具调用失败: not a valid value @ data['service']

我的热水器是一个Number类型的实体  input_number.set_value  然后设置为43 
之前14号的版本 如果设置温度 他会识别为 temperature  我使用“设置值为43”的话术 也会设置失败
今天等到18号的更新后 测试 看到这条日志
然后“调用服务” 关键词 我也没看到有 类似Number Set Value之类的服务调用 这个部分有可以参考的模版或者调用Service之类的实现么?
然后这个调用Service的操作 不会是挨个Api进行实现的吧? 那是在是辛苦大佬了

再次感谢大佬的组建😄

**Comment by knoop7** [comment]
正在解决，不管是gemini和chatgpt都很难彻底解决，总是会有错报的原因，可以逐步更新dev分支体验优化
